[prune]
  go-tests = true
  unused-packages = true
  non-go = true
  
  [[prune.project]]
    name = "github.com/kubernetes/dashboard"
    non-go = false
    unused-packages = false

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v10.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/browser"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/kubernetes/dashboard"
